package pl.infoshareacademy.webapp.statistics;

public enum StatisticEvents {
    CATEGORY1_CHOICE,
    CATEGORY2_CHOICE,
    CATEGORY3_SEARCH,
    CATEGORY4_SEARCH,

    MAIN_LINK,
    CATEGORY1_LINK,
    CATEGORY2_LINK,
    CATEGORY3_LINK,

    MENU_ENTRY,
    CATEGORY1_ENTRY,
    CATEGORY2_ENTRY,
    CATEGORY3_ENTRY,
    CATEGORY4_ENTRY,

}
