
package pl.infoshareacademy.webapp.allegro.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "servicePort", targetNamespace = "https://webapi.allegro.pl/service.php")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicePort {


    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoAddPackageInfoToPostBuyFormResponse
     */
    @WebMethod(action = "#doAddPackageInfoToPostBuyForm")
    @WebResult(name = "doAddPackageInfoToPostBuyFormResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoAddPackageInfoToPostBuyFormResponse doAddPackageInfoToPostBuyForm(
        @WebParam(name = "DoAddPackageInfoToPostBuyFormRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoAddPackageInfoToPostBuyFormRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoAddToBlackListResponse
     */
    @WebMethod(action = "#doAddToBlackList")
    @WebResult(name = "doAddToBlackListResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoAddToBlackListResponse doAddToBlackList(
        @WebParam(name = "DoAddToBlackListRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoAddToBlackListRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoBidItemResponse
     */
    @WebMethod(action = "#doBidItem")
    @WebResult(name = "doBidItemResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoBidItemResponse doBidItem(
        @WebParam(name = "DoBidItemRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoBidItemRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoCancelBidItemResponse
     */
    @WebMethod(action = "#doCancelBidItem")
    @WebResult(name = "doCancelBidItemResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoCancelBidItemResponse doCancelBidItem(
        @WebParam(name = "DoCancelBidItemRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoCancelBidItemRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoCancelRefundFormResponse
     */
    @WebMethod(action = "#doCancelRefundForm")
    @WebResult(name = "doCancelRefundFormResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoCancelRefundFormResponse doCancelRefundForm(
        @WebParam(name = "DoCancelRefundFormRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoCancelRefundFormRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoCancelRefundWarningResponse
     */
    @WebMethod(action = "#doCancelRefundWarning")
    @WebResult(name = "doCancelRefundWarningResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoCancelRefundWarningResponse doCancelRefundWarning(
        @WebParam(name = "DoCancelRefundWarningRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoCancelRefundWarningRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoCancelTransactionResponse
     */
    @WebMethod(action = "#doCancelTransaction")
    @WebResult(name = "doCancelTransactionResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoCancelTransactionResponse doCancelTransaction(
        @WebParam(name = "DoCancelTransactionRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoCancelTransactionRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoChangeItemFieldsResponse
     */
    @WebMethod(action = "#doChangeItemFields")
    @WebResult(name = "doChangeItemFieldsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoChangeItemFieldsResponse doChangeItemFields(
        @WebParam(name = "DoChangeItemFieldsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoChangeItemFieldsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoChangePriceItemResponse
     */
    @WebMethod(action = "#doChangePriceItem")
    @WebResult(name = "doChangePriceItemResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoChangePriceItemResponse doChangePriceItem(
        @WebParam(name = "DoChangePriceItemRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoChangePriceItemRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoChangeQuantityItemResponse
     */
    @WebMethod(action = "#doChangeQuantityItem")
    @WebResult(name = "doChangeQuantityItemResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoChangeQuantityItemResponse doChangeQuantityItem(
        @WebParam(name = "DoChangeQuantityItemRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoChangeQuantityItemRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoCheckItemDescriptionResponse
     */
    @WebMethod(action = "#doCheckItemDescription")
    @WebResult(name = "doCheckItemDescriptionResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoCheckItemDescriptionResponse doCheckItemDescription(
        @WebParam(name = "DoCheckItemDescriptionRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoCheckItemDescriptionRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoCheckNewAuctionExtResponse
     */
    @WebMethod(action = "#doCheckNewAuctionExt")
    @WebResult(name = "doCheckNewAuctionExtResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoCheckNewAuctionExtResponse doCheckNewAuctionExt(
        @WebParam(name = "DoCheckNewAuctionExtRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoCheckNewAuctionExtRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoCreateItemTemplateResponse
     */
    @WebMethod(action = "#doCreateItemTemplate")
    @WebResult(name = "doCreateItemTemplateResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoCreateItemTemplateResponse doCreateItemTemplate(
        @WebParam(name = "DoCreateItemTemplateRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoCreateItemTemplateRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoFinishItemResponse
     */
    @WebMethod(action = "#doFinishItem")
    @WebResult(name = "doFinishItemResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoFinishItemResponse doFinishItem(
        @WebParam(name = "DoFinishItemRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoFinishItemRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoFinishItemsResponse
     */
    @WebMethod(action = "#doFinishItems")
    @WebResult(name = "doFinishItemsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoFinishItemsResponse doFinishItems(
        @WebParam(name = "DoFinishItemsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoFinishItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetArchiveRefundsListResponse
     */
    @WebMethod(action = "#doGetArchiveRefundsList")
    @WebResult(name = "doGetArchiveRefundsListResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetArchiveRefundsListResponse doGetArchiveRefundsList(
        @WebParam(name = "DoGetArchiveRefundsListRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetArchiveRefundsListRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetBidItem2Response
     */
    @WebMethod(action = "#doGetBidItem2")
    @WebResult(name = "doGetBidItem2Response", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetBidItem2Response doGetBidItem2(
        @WebParam(name = "DoGetBidItem2Request", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetBidItem2Request parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetBlackListUsersResponse
     */
    @WebMethod(action = "#doGetBlackListUsers")
    @WebResult(name = "doGetBlackListUsersResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetBlackListUsersResponse doGetBlackListUsers(
        @WebParam(name = "DoGetBlackListUsersRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetBlackListUsersRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetCategoryPathResponse
     */
    @WebMethod(action = "#doGetCategoryPath")
    @WebResult(name = "doGetCategoryPathResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetCategoryPathResponse doGetCategoryPath(
        @WebParam(name = "DoGetCategoryPathRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetCategoryPathRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetCatsDataResponse
     */
    @WebMethod(action = "#doGetCatsData")
    @WebResult(name = "doGetCatsDataResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetCatsDataResponse doGetCatsData(
        @WebParam(name = "DoGetCatsDataRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetCatsDataRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetCatsDataCountResponse
     */
    @WebMethod(action = "#doGetCatsDataCount")
    @WebResult(name = "doGetCatsDataCountResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetCatsDataCountResponse doGetCatsDataCount(
        @WebParam(name = "DoGetCatsDataCountRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetCatsDataCountRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetCatsDataLimitResponse
     */
    @WebMethod(action = "#doGetCatsDataLimit")
    @WebResult(name = "doGetCatsDataLimitResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetCatsDataLimitResponse doGetCatsDataLimit(
        @WebParam(name = "DoGetCatsDataLimitRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetCatsDataLimitRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetCountriesResponse
     */
    @WebMethod(action = "#doGetCountries")
    @WebResult(name = "doGetCountriesResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetCountriesResponse doGetCountries(
        @WebParam(name = "DoGetCountriesRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetCountriesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetDealsResponse
     */
    @WebMethod(action = "#doGetDeals")
    @WebResult(name = "doGetDealsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetDealsResponse doGetDeals(
        @WebParam(name = "DoGetDealsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetDealsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetFilledPostBuyFormsResponse
     */
    @WebMethod(action = "#doGetFilledPostBuyForms")
    @WebResult(name = "doGetFilledPostBuyFormsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetFilledPostBuyFormsResponse doGetFilledPostBuyForms(
        @WebParam(name = "DoGetFilledPostBuyFormsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetFilledPostBuyFormsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetFreeDeliveryAmountResponse
     */
    @WebMethod(action = "#doGetFreeDeliveryAmount")
    @WebResult(name = "doGetFreeDeliveryAmountResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetFreeDeliveryAmountResponse doGetFreeDeliveryAmount(
        @WebParam(name = "DoGetFreeDeliveryAmountRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetFreeDeliveryAmountRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetItemFieldsResponse
     */
    @WebMethod(action = "#doGetItemFields")
    @WebResult(name = "doGetItemFieldsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetItemFieldsResponse doGetItemFields(
        @WebParam(name = "DoGetItemFieldsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetItemFieldsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetItemTemplatesResponse
     */
    @WebMethod(action = "#doGetItemTemplates")
    @WebResult(name = "doGetItemTemplatesResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetItemTemplatesResponse doGetItemTemplates(
        @WebParam(name = "DoGetItemTemplatesRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetItemTemplatesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetItemsImagesResponse
     */
    @WebMethod(action = "#doGetItemsImages")
    @WebResult(name = "doGetItemsImagesResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetItemsImagesResponse doGetItemsImages(
        @WebParam(name = "DoGetItemsImagesRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetItemsImagesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetItemsInfoResponse
     */
    @WebMethod(action = "#doGetItemsInfo")
    @WebResult(name = "doGetItemsInfoResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetItemsInfoResponse doGetItemsInfo(
        @WebParam(name = "DoGetItemsInfoRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetItemsInfoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetItemsListResponse
     */
    @WebMethod(action = "#doGetItemsList")
    @WebResult(name = "doGetItemsListResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetItemsListResponse doGetItemsList(
        @WebParam(name = "DoGetItemsListRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetItemsListRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetMessageToBuyerResponse
     */
    @WebMethod(action = "#doGetMessageToBuyer")
    @WebResult(name = "doGetMessageToBuyerResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMessageToBuyerResponse doGetMessageToBuyer(
        @WebParam(name = "DoGetMessageToBuyerRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetMessageToBuyerRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetMyAddressesResponse
     */
    @WebMethod(action = "#doGetMyAddresses")
    @WebResult(name = "doGetMyAddressesResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyAddressesResponse doGetMyAddresses(
        @WebParam(name = "DoGetMyAddressesRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetMyAddressesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetMyBidItemsResponse
     */
    @WebMethod(action = "#doGetMyBidItems")
    @WebResult(name = "doGetMyBidItemsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyBidItemsResponse doGetMyBidItems(
        @WebParam(name = "DoGetMyBidItemsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetMyBidItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetMyCurrentShipmentPriceTypeResponse
     */
    @WebMethod(action = "#doGetMyCurrentShipmentPriceType")
    @WebResult(name = "doGetMyCurrentShipmentPriceTypeResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyCurrentShipmentPriceTypeResponse doGetMyCurrentShipmentPriceType(
        @WebParam(name = "DoGetMyCurrentShipmentPriceTypeRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetMyCurrentShipmentPriceTypeRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetMyDataResponse
     */
    @WebMethod(action = "#doGetMyData")
    @WebResult(name = "doGetMyDataResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyDataResponse doGetMyData(
        @WebParam(name = "DoGetMyDataRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetMyDataRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetMyFutureItemsResponse
     */
    @WebMethod(action = "#doGetMyFutureItems")
    @WebResult(name = "doGetMyFutureItemsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyFutureItemsResponse doGetMyFutureItems(
        @WebParam(name = "DoGetMyFutureItemsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetMyFutureItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetMyIncomingPaymentsResponse
     */
    @WebMethod(action = "#doGetMyIncomingPayments")
    @WebResult(name = "doGetMyIncomingPaymentsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyIncomingPaymentsResponse doGetMyIncomingPayments(
        @WebParam(name = "DoGetMyIncomingPaymentsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetMyIncomingPaymentsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetMyIncomingPaymentsRefundsResponse
     */
    @WebMethod(action = "#doGetMyIncomingPaymentsRefunds")
    @WebResult(name = "doGetMyIncomingPaymentsRefundsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyIncomingPaymentsRefundsResponse doGetMyIncomingPaymentsRefunds(
        @WebParam(name = "DoGetMyIncomingPaymentsRefundsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetMyIncomingPaymentsRefundsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetMyNotSoldItemsResponse
     */
    @WebMethod(action = "#doGetMyNotSoldItems")
    @WebResult(name = "doGetMyNotSoldItemsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyNotSoldItemsResponse doGetMyNotSoldItems(
        @WebParam(name = "DoGetMyNotSoldItemsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetMyNotSoldItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetMyNotWonItemsResponse
     */
    @WebMethod(action = "#doGetMyNotWonItems")
    @WebResult(name = "doGetMyNotWonItemsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyNotWonItemsResponse doGetMyNotWonItems(
        @WebParam(name = "DoGetMyNotWonItemsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetMyNotWonItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetMyPaymentsResponse
     */
    @WebMethod(action = "#doGetMyPayments")
    @WebResult(name = "doGetMyPaymentsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyPaymentsResponse doGetMyPayments(
        @WebParam(name = "DoGetMyPaymentsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetMyPaymentsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetMyPaymentsInfoResponse
     */
    @WebMethod(action = "#doGetMyPaymentsInfo")
    @WebResult(name = "doGetMyPaymentsInfoResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyPaymentsInfoResponse doGetMyPaymentsInfo(
        @WebParam(name = "DoGetMyPaymentsInfoRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetMyPaymentsInfoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetMyPaymentsRefundsResponse
     */
    @WebMethod(action = "#doGetMyPaymentsRefunds")
    @WebResult(name = "doGetMyPaymentsRefundsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyPaymentsRefundsResponse doGetMyPaymentsRefunds(
        @WebParam(name = "DoGetMyPaymentsRefundsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetMyPaymentsRefundsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetMyPayoutsResponse
     */
    @WebMethod(action = "#doGetMyPayouts")
    @WebResult(name = "doGetMyPayoutsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyPayoutsResponse doGetMyPayouts(
        @WebParam(name = "DoGetMyPayoutsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetMyPayoutsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetMyPayoutsDetailsResponse
     */
    @WebMethod(action = "#doGetMyPayoutsDetails")
    @WebResult(name = "doGetMyPayoutsDetailsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyPayoutsDetailsResponse doGetMyPayoutsDetails(
        @WebParam(name = "DoGetMyPayoutsDetailsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetMyPayoutsDetailsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetMySellItemsResponse
     */
    @WebMethod(action = "#doGetMySellItems")
    @WebResult(name = "doGetMySellItemsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMySellItemsResponse doGetMySellItems(
        @WebParam(name = "DoGetMySellItemsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetMySellItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetMySoldItemsResponse
     */
    @WebMethod(action = "#doGetMySoldItems")
    @WebResult(name = "doGetMySoldItemsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMySoldItemsResponse doGetMySoldItems(
        @WebParam(name = "DoGetMySoldItemsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetMySoldItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetMyWonItemsResponse
     */
    @WebMethod(action = "#doGetMyWonItems")
    @WebResult(name = "doGetMyWonItemsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetMyWonItemsResponse doGetMyWonItems(
        @WebParam(name = "DoGetMyWonItemsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetMyWonItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetPaymentDataResponse
     */
    @WebMethod(action = "#doGetPaymentData")
    @WebResult(name = "doGetPaymentDataResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetPaymentDataResponse doGetPaymentData(
        @WebParam(name = "DoGetPaymentDataRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetPaymentDataRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetPaymentMethodsResponse
     */
    @WebMethod(action = "#doGetPaymentMethods")
    @WebResult(name = "doGetPaymentMethodsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetPaymentMethodsResponse doGetPaymentMethods(
        @WebParam(name = "DoGetPaymentMethodsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetPaymentMethodsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetPostBuyDataResponse
     */
    @WebMethod(action = "#doGetPostBuyData")
    @WebResult(name = "doGetPostBuyDataResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetPostBuyDataResponse doGetPostBuyData(
        @WebParam(name = "DoGetPostBuyDataRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetPostBuyDataRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetPostBuyFormsDataForBuyersResponse
     */
    @WebMethod(action = "#doGetPostBuyFormsDataForBuyers")
    @WebResult(name = "doGetPostBuyFormsDataForBuyersResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetPostBuyFormsDataForBuyersResponse doGetPostBuyFormsDataForBuyers(
        @WebParam(name = "DoGetPostBuyFormsDataForBuyersRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetPostBuyFormsDataForBuyersRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetPostBuyFormsDataForSellersResponse
     */
    @WebMethod(action = "#doGetPostBuyFormsDataForSellers")
    @WebResult(name = "doGetPostBuyFormsDataForSellersResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetPostBuyFormsDataForSellersResponse doGetPostBuyFormsDataForSellers(
        @WebParam(name = "DoGetPostBuyFormsDataForSellersRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetPostBuyFormsDataForSellersRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetPostBuyFormsIdsResponse
     */
    @WebMethod(action = "#doGetPostBuyFormsIds")
    @WebResult(name = "doGetPostBuyFormsIdsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetPostBuyFormsIdsResponse doGetPostBuyFormsIds(
        @WebParam(name = "DoGetPostBuyFormsIdsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetPostBuyFormsIdsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetPostBuyItemInfoResponse
     */
    @WebMethod(action = "#doGetPostBuyItemInfo")
    @WebResult(name = "doGetPostBuyItemInfoResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetPostBuyItemInfoResponse doGetPostBuyItemInfo(
        @WebParam(name = "DoGetPostBuyItemInfoRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetPostBuyItemInfoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetRefundsDealsResponse
     */
    @WebMethod(action = "#doGetRefundsDeals")
    @WebResult(name = "doGetRefundsDealsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetRefundsDealsResponse doGetRefundsDeals(
        @WebParam(name = "DoGetRefundsDealsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetRefundsDealsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetRefundsListResponse
     */
    @WebMethod(action = "#doGetRefundsList")
    @WebResult(name = "doGetRefundsListResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetRefundsListResponse doGetRefundsList(
        @WebParam(name = "DoGetRefundsListRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetRefundsListRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetRefundsReasonsResponse
     */
    @WebMethod(action = "#doGetRefundsReasons")
    @WebResult(name = "doGetRefundsReasonsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetRefundsReasonsResponse doGetRefundsReasons(
        @WebParam(name = "DoGetRefundsReasonsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetRefundsReasonsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetRelatedItemsResponse
     */
    @WebMethod(action = "#doGetRelatedItems")
    @WebResult(name = "doGetRelatedItemsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetRelatedItemsResponse doGetRelatedItems(
        @WebParam(name = "DoGetRelatedItemsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetRelatedItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetSellFormFieldsForCategoryResponse
     */
    @WebMethod(action = "#doGetSellFormFieldsForCategory")
    @WebResult(name = "doGetSellFormFieldsForCategoryResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetSellFormFieldsForCategoryResponse doGetSellFormFieldsForCategory(
        @WebParam(name = "DoGetSellFormFieldsForCategoryRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetSellFormFieldsForCategoryRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetSessionHandleForWidgetResponse
     */
    @WebMethod(action = "#doGetSessionHandleForWidget")
    @WebResult(name = "doGetSessionHandleForWidgetResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetSessionHandleForWidgetResponse doGetSessionHandleForWidget(
        @WebParam(name = "DoGetSessionHandleForWidgetRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetSessionHandleForWidgetRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetShipmentDataResponse
     */
    @WebMethod(action = "#doGetShipmentData")
    @WebResult(name = "doGetShipmentDataResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetShipmentDataResponse doGetShipmentData(
        @WebParam(name = "DoGetShipmentDataRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetShipmentDataRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetShipmentDataForRelatedItemsResponse
     */
    @WebMethod(action = "#doGetShipmentDataForRelatedItems")
    @WebResult(name = "doGetShipmentDataForRelatedItemsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetShipmentDataForRelatedItemsResponse doGetShipmentDataForRelatedItems(
        @WebParam(name = "DoGetShipmentDataForRelatedItemsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetShipmentDataForRelatedItemsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetShipmentPriceTypesResponse
     */
    @WebMethod(action = "#doGetShipmentPriceTypes")
    @WebResult(name = "doGetShipmentPriceTypesResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetShipmentPriceTypesResponse doGetShipmentPriceTypes(
        @WebParam(name = "DoGetShipmentPriceTypesRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetShipmentPriceTypesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetShopsTagsResponse
     */
    @WebMethod(action = "#doGetShopsTags")
    @WebResult(name = "doGetShopsTagsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetShopsTagsResponse doGetShopsTags(
        @WebParam(name = "DoGetShopsTagsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetShopsTagsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetSiteJournalResponse
     */
    @WebMethod(action = "#doGetSiteJournal")
    @WebResult(name = "doGetSiteJournalResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetSiteJournalResponse doGetSiteJournal(
        @WebParam(name = "DoGetSiteJournalRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetSiteJournalRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetSiteJournalDealsResponse
     */
    @WebMethod(action = "#doGetSiteJournalDeals")
    @WebResult(name = "doGetSiteJournalDealsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetSiteJournalDealsResponse doGetSiteJournalDeals(
        @WebParam(name = "DoGetSiteJournalDealsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetSiteJournalDealsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetSiteJournalDealsInfoResponse
     */
    @WebMethod(action = "#doGetSiteJournalDealsInfo")
    @WebResult(name = "doGetSiteJournalDealsInfoResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetSiteJournalDealsInfoResponse doGetSiteJournalDealsInfo(
        @WebParam(name = "DoGetSiteJournalDealsInfoRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetSiteJournalDealsInfoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetSiteJournalInfoResponse
     */
    @WebMethod(action = "#doGetSiteJournalInfo")
    @WebResult(name = "doGetSiteJournalInfoResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetSiteJournalInfoResponse doGetSiteJournalInfo(
        @WebParam(name = "DoGetSiteJournalInfoRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetSiteJournalInfoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetStatesInfoResponse
     */
    @WebMethod(action = "#doGetStatesInfo")
    @WebResult(name = "doGetStatesInfoResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetStatesInfoResponse doGetStatesInfo(
        @WebParam(name = "DoGetStatesInfoRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetStatesInfoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetSystemTimeResponse
     */
    @WebMethod(action = "#doGetSystemTime")
    @WebResult(name = "doGetSystemTimeResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetSystemTimeResponse doGetSystemTime(
        @WebParam(name = "DoGetSystemTimeRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetSystemTimeRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetTransactionsIDsResponse
     */
    @WebMethod(action = "#doGetTransactionsIDs")
    @WebResult(name = "doGetTransactionsIDsResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetTransactionsIDsResponse doGetTransactionsIDs(
        @WebParam(name = "DoGetTransactionsIDsRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetTransactionsIDsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetUserIDResponse
     */
    @WebMethod(action = "#doGetUserID")
    @WebResult(name = "doGetUserIDResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetUserIDResponse doGetUserID(
        @WebParam(name = "DoGetUserIDRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetUserIDRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoGetUserLoginResponse
     */
    @WebMethod(action = "#doGetUserLogin")
    @WebResult(name = "doGetUserLoginResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoGetUserLoginResponse doGetUserLogin(
        @WebParam(name = "DoGetUserLoginRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoGetUserLoginRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoLoginResponse
     */
    @WebMethod(action = "#doLogin")
    @WebResult(name = "doLoginResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoLoginResponse doLogin(
        @WebParam(name = "DoLoginRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoLoginRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoLoginEncResponse
     */
    @WebMethod(action = "#doLoginEnc")
    @WebResult(name = "doLoginEncResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoLoginEncResponse doLoginEnc(
        @WebParam(name = "DoLoginEncRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoLoginEncRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoLoginWithAccessTokenResponse
     */
    @WebMethod(action = "#doLoginWithAccessToken")
    @WebResult(name = "doLoginWithAccessTokenResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoLoginWithAccessTokenResponse doLoginWithAccessToken(
        @WebParam(name = "DoLoginWithAccessTokenRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoLoginWithAccessTokenRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoMyAccount2Response
     */
    @WebMethod(action = "#doMyAccount2")
    @WebResult(name = "doMyAccount2Response", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoMyAccount2Response doMyAccount2(
        @WebParam(name = "DoMyAccount2Request", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoMyAccount2Request parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoMyAccountItemsCountResponse
     */
    @WebMethod(action = "#doMyAccountItemsCount")
    @WebResult(name = "doMyAccountItemsCountResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoMyAccountItemsCountResponse doMyAccountItemsCount(
        @WebParam(name = "DoMyAccountItemsCountRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoMyAccountItemsCountRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoMyBillingResponse
     */
    @WebMethod(action = "#doMyBilling")
    @WebResult(name = "doMyBillingResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoMyBillingResponse doMyBilling(
        @WebParam(name = "DoMyBillingRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoMyBillingRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoMyBillingItemResponse
     */
    @WebMethod(action = "#doMyBillingItem")
    @WebResult(name = "doMyBillingItemResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoMyBillingItemResponse doMyBillingItem(
        @WebParam(name = "DoMyBillingItemRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoMyBillingItemRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoMyContactResponse
     */
    @WebMethod(action = "#doMyContact")
    @WebResult(name = "doMyContactResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoMyContactResponse doMyContact(
        @WebParam(name = "DoMyContactRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoMyContactRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoNewAuctionExtResponse
     */
    @WebMethod(action = "#doNewAuctionExt")
    @WebResult(name = "doNewAuctionExtResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoNewAuctionExtResponse doNewAuctionExt(
        @WebParam(name = "DoNewAuctionExtRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoNewAuctionExtRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoQueryAllSysStatusResponse
     */
    @WebMethod(action = "#doQueryAllSysStatus")
    @WebResult(name = "doQueryAllSysStatusResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoQueryAllSysStatusResponse doQueryAllSysStatus(
        @WebParam(name = "DoQueryAllSysStatusRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoQueryAllSysStatusRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoQuerySysStatusResponse
     */
    @WebMethod(action = "#doQuerySysStatus")
    @WebResult(name = "doQuerySysStatusResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoQuerySysStatusResponse doQuerySysStatus(
        @WebParam(name = "DoQuerySysStatusRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoQuerySysStatusRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoRemoveFromBlackListResponse
     */
    @WebMethod(action = "#doRemoveFromBlackList")
    @WebResult(name = "doRemoveFromBlackListResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoRemoveFromBlackListResponse doRemoveFromBlackList(
        @WebParam(name = "DoRemoveFromBlackListRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoRemoveFromBlackListRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoRemoveItemTemplatesResponse
     */
    @WebMethod(action = "#doRemoveItemTemplates")
    @WebResult(name = "doRemoveItemTemplatesResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoRemoveItemTemplatesResponse doRemoveItemTemplates(
        @WebParam(name = "DoRemoveItemTemplatesRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoRemoveItemTemplatesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoRequestCancelBidResponse
     */
    @WebMethod(action = "#doRequestCancelBid")
    @WebResult(name = "doRequestCancelBidResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoRequestCancelBidResponse doRequestCancelBid(
        @WebParam(name = "DoRequestCancelBidRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoRequestCancelBidRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoRequestPayoutResponse
     */
    @WebMethod(action = "#doRequestPayout")
    @WebResult(name = "doRequestPayoutResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoRequestPayoutResponse doRequestPayout(
        @WebParam(name = "DoRequestPayoutRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoRequestPayoutRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoRequestSurchargeResponse
     */
    @WebMethod(action = "#doRequestSurcharge")
    @WebResult(name = "doRequestSurchargeResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoRequestSurchargeResponse doRequestSurcharge(
        @WebParam(name = "DoRequestSurchargeRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoRequestSurchargeRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoSellSomeAgainResponse
     */
    @WebMethod(action = "#doSellSomeAgain")
    @WebResult(name = "doSellSomeAgainResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoSellSomeAgainResponse doSellSomeAgain(
        @WebParam(name = "DoSellSomeAgainRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoSellSomeAgainRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoSellSomeAgainInShopResponse
     */
    @WebMethod(action = "#doSellSomeAgainInShop")
    @WebResult(name = "doSellSomeAgainInShopResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoSellSomeAgainInShopResponse doSellSomeAgainInShop(
        @WebParam(name = "DoSellSomeAgainInShopRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoSellSomeAgainInShopRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoSendEmailToUserResponse
     */
    @WebMethod(action = "#doSendEmailToUser")
    @WebResult(name = "doSendEmailToUserResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoSendEmailToUserResponse doSendEmailToUser(
        @WebParam(name = "DoSendEmailToUserRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoSendEmailToUserRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoSendPostBuyFormResponse
     */
    @WebMethod(action = "#doSendPostBuyForm")
    @WebResult(name = "doSendPostBuyFormResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoSendPostBuyFormResponse doSendPostBuyForm(
        @WebParam(name = "DoSendPostBuyFormRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoSendPostBuyFormRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoSendRefundFormResponse
     */
    @WebMethod(action = "#doSendRefundForm")
    @WebResult(name = "doSendRefundFormResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoSendRefundFormResponse doSendRefundForm(
        @WebParam(name = "DoSendRefundFormRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoSendRefundFormRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoSetFreeDeliveryAmountResponse
     */
    @WebMethod(action = "#doSetFreeDeliveryAmount")
    @WebResult(name = "doSetFreeDeliveryAmountResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoSetFreeDeliveryAmountResponse doSetFreeDeliveryAmount(
        @WebParam(name = "DoSetFreeDeliveryAmountRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoSetFreeDeliveryAmountRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoSetShipmentPriceTypeResponse
     */
    @WebMethod(action = "#doSetShipmentPriceType")
    @WebResult(name = "doSetShipmentPriceTypeResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoSetShipmentPriceTypeResponse doSetShipmentPriceType(
        @WebParam(name = "DoSetShipmentPriceTypeRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoSetShipmentPriceTypeRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoShowItemInfoExtResponse
     */
    @WebMethod(action = "#doShowItemInfoExt")
    @WebResult(name = "doShowItemInfoExtResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoShowItemInfoExtResponse doShowItemInfoExt(
        @WebParam(name = "DoShowItemInfoExtRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoShowItemInfoExtRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoShowUserResponse
     */
    @WebMethod(action = "#doShowUser")
    @WebResult(name = "doShowUserResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoShowUserResponse doShowUser(
        @WebParam(name = "DoShowUserRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoShowUserRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns api.DoVerifyItemResponse
     */
    @WebMethod(action = "#doVerifyItem")
    @WebResult(name = "doVerifyItemResponse", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
    public DoVerifyItemResponse doVerifyItem(
        @WebParam(name = "DoVerifyItemRequest", targetNamespace = "https://webapi.allegro.pl/service.php", partName = "parameters")
        DoVerifyItemRequest parameters);

}
