version: "3"
services:
  app:
   - container_name: "webapp"
   - build: ../jjdd2-gang-swiezakow
networks:
	-frontend
	-backend

    ports:
    -  8080
    -  9990
    depends_on:
      - db
  db:
    container_name: "db"
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=zakupydb

	networks:
	-backend
	ports:
      - 3306:3306
networks:
	frontend:
driver: bridge

	backend:
driver:bridge